<?php
/**
 * Define an achievement.
 *
 * This hook describes your achievements to the base module so that it can
 * create the pages and caches necessary for site-wide display. The base
 * module doesn't know how to unlock any of your achievements... instead, you
 * use Drupal's existing hooks, the achievement storage tables, and a few
 * helper functions to complete the workflow. See the remaining documentation
 * in this file for further code samples.
 *
 * There are many different kinds of achievements, and it's accurate enough to
 * say that if you can measure or respond to an action, it can be made into a
 * matching achievement. Be creative. Look at what others are doing. Have fun.
 * Your gamification efforts will fail or be un-fun if you don't have a gamer
 * helping you, if you make everything a mindless grind, or if you simply
 * copy achievements from another site or install.
 *
 * @return
 *   An array whose keys are internal achievement IDs (32 chars max) and whose
 *   values identify properties of the achievement. These properties are:
 *   - title: (required) The title of the achievement.
 *   - description: (required) A description of the achievement.
 *   - points: (required) How many points the user will earn when unlocked.
 *   - images: (optional) An array of (optional) keys 'locked', 'unlocked',
 *     and 'secret' whose values are image file paths. Achievements exist in
 *     three separate display states: unlocked (the user has it), locked (the
 *     user doesn't have it), and secret (the user doesn't have it, and the
 *     achievement is a secret). Each state can have its own default image
 *     associated with it (which administrators can configure), or achievements
 *     can specify their own images for one, some, or all states.
 *   - storage: (optional) If you store statistics for your achievement, the
 *     core module assumes you've used the achievement ID for the storage
 *     location. If you haven't, specify the storage location here. This lets
 *     the core module know what to delete when an administrator manually
 *     removes an achievement unlock from a user. If your achievement
 *     tracks statistics that are NOT set with achievements_storage_get()
 *     or _set, you don't have to define the 'storage' key.
 *   - secret: (optional) The achievement displays on a user's Achievements
 *     tab but does not reveal its title, description, or points until the
 *     user has unlocked it. Compatible with 'invisible'.
 *   - invisible: (optional) The achievement does NOT display on a user's
 *     Achievements tab, but does show up on the leaderboards when necessary.
 *     Compatible with 'secret' (i.e., if another user has unlocked an
 *     invisible achievement, a user who has not unlocked it will see the
 *     placeholder secret text instead of the actual achievement itself).
 *
 *   Achievements can also be categorized into groups. Groups are simply
 *   arrays whose keys are internal group IDs and whose values identify
 *   the 'title' of the group as well as the array of 'achievements' that
 *   correspond to that group. If some achievements are within a group and
 *   some achievements are without a group, the groupless achievements will
 *   automatically be placed into a "Miscellany" category.
 */
function coderdojo_ic_achievements_info() {
  $achievements = array(
    'belts' => array(
      'title'=>'Belts',
      'achievements' => array(
        'belt_white' => array(
          'title'       => t('White Belt (Initiate)'),
          'description' => t("Attended CoderDojo for 5 sessions"),
          'points'      => 20,
          'images' => array(
            'locked'  => '/sites/default/achievements/default_70_grey.png',
            'unlocked'  => '/sites/default/achievements/belts/white.png'
          ),
        ),
        'belt_yellow' => array(
          'title'       => t('Yellow Belt (Trainee)'),
          'description' => t("Obtained White belt and 5 basic badges"),
          'points'      => 200,
          'images' => array(
            'locked'  => '/sites/default/achievements/default_70_grey.png',
            'unlocked'  => '/sites/default/achievements/belts/yellow.png'
          ),
        ),
        'belt_blue' => array(
          'title'       => t('Blue Belt (Adherent)'),
          'description' => t("Obtained Yellow belt, 1 junior badges and 3 basic badges"),
          'points'      => 300,
          'images' => array(
            'locked'  => '/sites/default/achievements/default_70_grey.png',
            'unlocked'  => '/sites/default/achievements/belts/blue.png'
          ),
        ),
        'belt_red' => array(
          'title'       => t('Red Belt (Apprentice)'),
          'description' => t("Obtained Blue belt, 3 junior badges and 1 senior badge"),
          'points'      => 500,
          'images' => array(
            'locked'  => '/sites/default/achievements/default_70_grey.png',
            'unlocked'  => '/sites/default/achievements/belts/red.png'
          ),
        ),
        'belt_black' => array(
          'title'       => t('Black Belt (Master)'),
          'description' => t("Obtained Red belt and 4 senior badges"),
          'points'      => 1000,
          'images' => array(
            'locked'  => '/sites/default/achievements/default_70_grey.png',
            'unlocked'  => '/sites/default/achievements/belts/black.png'
          ),
        ),
      ),
    ),
    'badges' => array(
      'title'=>'Badges',
      'achievements' => array(
        // HTML5
        'html5_basic' => array(
          'title'       => t('Basic HTML5'),
          'description' => t('Completed basic HTML5 application'),
          'points'      => 10,
          'images' => array(
            'locked'  => '/sites/default/achievements/default_70_grey.png',
            'unlocked'  => '/sites/default/achievements/badges/html5/html5_basic.png'
          ),
        ),
        'html5_junior' => array(
          'title'       => t('Junior HTML5'),
          'description' => t('Completed junior HTML5 application'),
          'points'      => 10,
          'images' => array(
            'locked'  => '/sites/default/achievements/default_70_grey.png',
            'unlocked'  => '/sites/default/achievements/badges/html5/html5_junior.png'
          ),
        ),
        'html5_senior' => array(
          'title'       => t('Senior HTML5'),
          'description' => t('Completed senior HTML5 application'),
          'points'      => 10,
          'images' => array(
            'locked'  => '/sites/default/achievements/default_70_grey.png',
            'unlocked'  => '/sites/default/achievements/badges/html5/html5_senior.png'
          ),
        ),
        // Java
        'java_basic' => array(
          'title'       => t('Basic Java'),
          'description' => t('Completed basic Java application'),
          'points'      => 10,
          'images' => array(
            'locked'  => '/sites/default/achievements/default_70_grey.png',
            'unlocked'  => '/sites/default/achievements/badges/java/java_basic.png'
          ),
        ),
        'java_junior' => array(
          'title'       => t('Junior Java'),
          'description' => t('Completed junior Java application'),
          'points'      => 10,
          'images' => array(
            'locked'  => '/sites/default/achievements/default_70_grey.png',
            'unlocked'  => '/sites/default/achievements/badges/java/java_junior.png'
          ),
        ),
        'java_senior' => array(
          'title'       => t('Senior Java'),
          'description' => t('Completed senior Java application'),
          'points'      => 10,
          'images' => array(
            'locked'  => '/sites/default/achievements/default_70_grey.png',
            'unlocked'  => '/sites/default/achievements/badges/java/java_senior.png'
          ),
        ),
        'java_minecraft_modder' => array(
          'title'       => t('Minecraft Modder'),
          'description' => t('Completed Minecraft modding application'),
          'points'      => 10,
          'images' => array(
            'locked'  => '/sites/default/achievements/default_70_grey.png',
            'unlocked'  => '/sites/default/achievements/badges/java/java_minecraft_modder.png'
          ),
        ),
        // JS
        'javascript_basic' => array(
          'title'       => t('Basic JavaScript'),
          'description' => t('Completed basic JavaScript application'),
          'points'      => 10,
          'images' => array(
            'locked'  => '/sites/default/achievements/default_70_grey.png',
            'unlocked'  => '/sites/default/achievements/badges/javascript/javascript_basic.png'
          ),
        ),
        'javascript_junior' => array(
          'title'       => t('Junior JavaScript'),
          'description' => t('Completed junior JavaScript application'),
          'points'      => 10,
          'images' => array(
            'locked'  => '/sites/default/achievements/default_70_grey.png',
            'unlocked'  => '/sites/default/achievements/badges/javascript/javascript_junior.png'
          ),
        ),
        'javascript_senior' => array(
          'title'       => t('Senior JavaScript'),
          'description' => t('Completed senior JavaScript application'),
          'points'      => 10,
          'images' => array(
            'locked'  => '/sites/default/achievements/default_70_grey.png',
            'unlocked'  => '/sites/default/achievements/badges/javascript/javascript_senior.png'
          ),
        ),

      ),
    ),
  );

    // An example of achievement groups: 'article-creation' is the group ID,
    // "Article creation" is the group title, and all relevant achievements are
    // placed in an 'achievements' array. The ungrouped comment achievements
    // above will be automatically pushed into a "Miscellany" group.
  /*  'article-creation' => array(
      'title' => t('Article creation'),
      'achievements' => array(HTML5_1
        'node-mondays' => array(
          'title'       => t('Published some content on a Monday'),
          'description' => t("Go back to bed: it's still the weekend!"),
          'points'      => 5,
          'images' => array(
            'unlocked'  => '/sites/default/files/example1.png',
            'locked'    => '/sites/default/files/example2.png',
            'secret'    => '/sites/default/files/example3.png'
            // all default images have been replaced.
          ),
        ),
      ),
    ),
  );
  */

  return $achievements;
}
