<?php
/**
* @file
* Badges and hooks for CoderDojo
* See achievements.api.php for more info
*/

function coderdojo_ic_achievements_info() {
  $achievements = array(
    'belts' => array(
      'title'=>'Belts',
      'achievements' => array(
        'belt_white' => array(
          'title'       => t('White Belt (Initiate)'),
          'description' => t("Attended CoderDojo for 5 sessions"),
          'points'      => 10,
          'storage'     => 'belt_count',
          'images' => array(
            'locked'  => '/sites/default/achievements/default_70_grey.png',
            'unlocked'  => '/sites/default/achievements/belts/white.png'
          ),
        ),
        'belt_yellow' => array(
          'title'       => t('Yellow Belt (Trainee)'),
          'description' => t("Obtained White belt and 5 basic badges"),
          'points'      => 200,
          'storage'     => 'belt_count',
          'images' => array(
            'locked'  => '/sites/default/achievements/default_70_grey.png',
            'unlocked'  => '/sites/default/achievements/belts/yellow.png'
          ),
        ),
        'belt_blue' => array(
          'title'       => t('Blue Belt (Adherent)'),
          'description' => t("Obtained Yellow belt, 1 junior badges and 3 basic badges"),
          'points'      => 300,
          'storage'     => 'belt_count',
          'images' => array(
            'locked'  => '/sites/default/achievements/default_70_grey.png',
            'unlocked'  => '/sites/default/achievements/belts/blue.png'
          ),
        ),
        'belt_red' => array(
          'title'       => t('Red Belt (Apprentice)'),
          'description' => t("Obtained Blue belt, 3 junior badges and 1 senior badge"),
          'points'      => 500,
          'storage'     => 'belt_count',
          'images' => array(
            'locked'  => '/sites/default/achievements/default_70_grey.png',
            'unlocked'  => '/sites/default/achievements/belts/red.png'
          ),
        ),
        'belt_black' => array(
          'title'       => t('Black Belt (Master)'),
          'description' => t("Obtained Red belt and 4 senior badges"),
          'points'      => 1000,
          'storage'     => 'belt_count',
          'images' => array(
            'locked'  => '/sites/default/achievements/default_70_grey.png',
            'unlocked'  => '/sites/default/achievements/belts/black.png'
          ),
        ),
      ),
    ),
    'badges' => array(
      'title'=>'Badges',
      'achievements' => array(
        // HTML5
        'html5_basic' => array(
          'title'       => t('Basic HTML5'),
          'description' => t('Completed basic HTML5 application'),
          'points'      => 20,
          'storage'     => 'basic_badge_count',
          'images' => array(
            'locked'  => '/sites/default/achievements/default_70_grey.png',
            'unlocked'  => '/sites/default/achievements/badges/html5/html5_basic.png'
          ),
        ),
        'html5_junior' => array(
          'title'       => t('Junior HTML5'),
          'description' => t('Completed junior HTML5 application'),
          'points'      => 20,
          'storage'     => 'junior_badge_count',
          'images' => array(
            'locked'  => '/sites/default/achievements/default_70_grey.png',
            'unlocked'  => '/sites/default/achievements/badges/html5/html5_junior.png'
          ),
        ),
        'html5_senior' => array(
          'title'       => t('Senior HTML5'),
          'description' => t('Completed senior HTML5 application'),
          'points'      => 20,
          'storage'     => 'senior_badge_count',
          'images' => array(
            'locked'  => '/sites/default/achievements/default_70_grey.png',
            'unlocked'  => '/sites/default/achievements/badges/html5/html5_senior.png'
          ),
        ),
        // Java
        'java_basic' => array(
          'title'       => t('Basic Java'),
          'description' => t('Completed basic Java application'),
          'points'      => 20,
          'storage'     => 'basic_badge_count',
          'images' => array(
            'locked'  => '/sites/default/achievements/default_70_grey.png',
            'unlocked'  => '/sites/default/achievements/badges/java/java_basic.png'
          ),
        ),
        'java_junior' => array(
          'title'       => t('Junior Java'),
          'description' => t('Completed junior Java application'),
          'points'      => 20,
          'storage'     => 'junior_badge_count',
          'images' => array(
            'locked'  => '/sites/default/achievements/default_70_grey.png',
            'unlocked'  => '/sites/default/achievements/badges/java/java_junior.png'
          ),
        ),
        'java_senior' => array(
          'title'       => t('Senior Java'),
          'description' => t('Completed senior Java application'),
          'points'      => 20,
          'storage'     => 'senior_badge_count',
          'images' => array(
            'locked'  => '/sites/default/achievements/default_70_grey.png',
            'unlocked'  => '/sites/default/achievements/badges/java/java_senior.png'
          ),
        ),
        'java_minecraft_modder' => array(
          'title'       => t('Minecraft Modder'),
          'description' => t('Completed Minecraft modding application'),
          'points'      => 20,
          'storage'     => 'other_badge_count',
          'images' => array(
            'locked'  => '/sites/default/achievements/default_70_grey.png',
            'unlocked'  => '/sites/default/achievements/badges/java/java_minecraft_modder.png'
          ),
        ),
        // JS
        'javascript_basic' => array(
          'title'       => t('Basic JavaScript'),
          'description' => t('Completed basic JavaScript application'),
          'points'      => 20,
          'storage'     => 'basic_badge_count',
          'images' => array(
            'locked'  => '/sites/default/achievements/default_70_grey.png',
            'unlocked'  => '/sites/default/achievements/badges/javascript/javascript_basic.png'
          ),
        ),
        'javascript_junior' => array(
          'title'       => t('Junior JavaScript'),
          'description' => t('Completed junior JavaScript application'),
          'points'      => 20,
          'storage'     => 'junior_badge_count',
          'images' => array(
            'locked'  => '/sites/default/achievements/default_70_grey.png',
            'unlocked'  => '/sites/default/achievements/badges/javascript/javascript_junior.png'
          ),
        ),
        'javascript_senior' => array(
          'title'       => t('Senior JavaScript'),
          'description' => t('Completed senior JavaScript application'),
          'points'      => 20,
          'storage'     => 'senior_badge_count',
          'images' => array(
            'locked'  => '/sites/default/achievements/default_70_grey.png',
            'unlocked'  => '/sites/default/achievements/badges/javascript/javascript_senior.png'
          ),
        ),
      ),
    ),
  );

  return $achievements;
}


/**
 * Implements hook_belts_unlocked().
 *
 * This hook is invoked after an achievement has been unlocked and all
 * the relevant information has been stored or updated in the database.
 *
 * @param $achievement
 *  An array of information about the achievement.
 * @param $uid
 *  The user ID who has unlocked the achievement.
 */
function hook_belts_unlocked($achievement, $uid) {
  if (strpos($achievement->id, 'belt') !== FALSE) {
      // EMAIL parents/mentors to set awards date
  }
  else {
     // They have earned a badge
     // Check if they have earned a belt
     $current_belt = achievements_storage_get('belt_count', $uid);
     $current_basic = achievements_storage_get('basic_badge_count', $uid);
     $current_junior = achievements_storage_get('junior_badge_count', $uid);
     $current_senior = achievements_storage_get('senior_badge_count', $uid);
     $current_social = achievements_storage_get('social_badge_count', $uid);
     // TODO: Add attendence variable and check
     // if ( ($current_belt == 0) && ($attendance >= 5) ) {
     if ($current_belt == 0) {
         // Earn white
         acheivements_unlocked('belt_white', $uid);
     } elseif (($current_belt == 1) && ($current_basic >= 5) && ($current_social == 1)) {
         // Earn yellow
         acheivements_unlocked('belt_yellow', $uid);
     } elseif (($current_belt == 2) && ($current_basic >= 8) && ($current_junior >= 1) && ($current_social == 2)) {
         // Earn blue
         acheivements_unlocked('belt_blue', $uid);
     } elseif (($current_belt == 3) && ($current_junior >= 4) && ($current_senior >= 1) && ($current_social == 3)) {
         // Earn red
         acheivements_unlocked('belt_red', $uid);
     } elseif (($current_belt == 4) && ($current_senior >= 5) && ($current_social == 4)) {
         // Earn black
         acheivements_unlocked('belt_black', $uid);
         // TODO: Do something huge: tweet, email all members, explode, etc.
     }
  }
}


/**
 * Implements hook_achievements_access_earn().
 *
 * Allows you to programmatically determine if a user has access to earn
 * achievements. We do already have an "earn achievements" permission, but
 * this allows more complex methods of determining that privilege. For an
 * example, see the achievements_optout.module, which allows a user to opt-out
 * of earning achievements, even if you've already granted them permission to.
 *
 * @param $uid
 *   The user ID whose access is being questioned.
 *
 * @return
 *   TRUE if the $uid can earn achievements, FALSE if they can't,
 *   or NULL if there's no change to the user's default access.
 */
function achievements_access_earn($uid) {
  $account = user_load($uid);
  if ($account->role == 'student') {
    return TRUE;
  }
}